### ISSUE TITLE
generateEpub.js has incorrect page numbers

### ISSUE THREAD

**Issue by Funtime60** [danbulant/Mangades#10]
At [Line 75](https://github.com/danbulant/Mangades/blob/56562f88ca2fdf81ef8d888feb24dbcc1b472cb1/src/lib/util/generateEpub.js#L75) in [generateEpub.js](https://github.com/danbulant/Mangades/blob/master/src/lib/util/generateEpub.js) it concatenates a 1 onto the end of the page number.

This doesn't make much sense and seems like it was intended to add a 1 rather than concatenate.

**Comment by danbulant** [comment]
Fixed by #b79647d
