### ISSUE TITLE
Select All button is not working

### ISSUE THREAD

**Issue by Methaneus** [danbulant/Mangades#2]
The Select All Button does nothing.

Tested on:
Microsoft Edge, Version 98.0.1108.56 (Official build) (64-bit)
Waterfox G4.0.6 (Firefox).

**Comment by danbulant** [comment]
Can you send a link to an example page where it doesn't work?
https://manga.danbulant.eu/a96676e5-8ae2-425e-b549-7f15dd34a6d8 works on Edge, Vivaldi and Firefox

**Comment by danbulant** [comment]
Closing for lack of information
