### ISSUE TITLE
Website not loading comics past ch.86

### ISSUE THREAD

**Issue by Z1ppr** [danbulant/Mangades#5]
The website doesn't load from bilibili comics on [Busted! Darklord!](https://manga.danbulant.eu/310d5beb-79fd-4a48-a028-95a016307efb). It only loads the ones from "Virgin's Ear" which go to ch.86.

Tested on:
Google Chrome, Version 102.0.5005.63 (Official Build) (64-bit).

**Comment by danbulant** [comment]
This is just a mangadex client with simplified graphics ("Screen reader optimized") and an option to easily download the chapters (as CBZ or EPUB). You can check [here](https://mangadex.org/title/310d5beb-79fd-4a48-a028-95a016307efb) that mangadex also has only chapters up to 86.
Note that mangadex is not a piracy site, but rather a community forum for sharing translations - stolen translations are deleted from there if the authors of the translation don't want to be featured there.
You can try asking the translation authors if they want to submit to mangadex - it should appear almost immediately on this site as well as it gets all the images and chapters from mangadex.

**Comment by Z1ppr** [comment]
@danbulant Sorry, I guess the translation that went farther than the other one was removed, as before there where 2 scantalation groups and a one when to ch.149 but that group was removed from this series recently.
