### ISSUE TITLE
Pages are downloading a placeholder image

### ISSUE THREAD

**Issue by jonnyli** [danbulant/Mangades#7]
No image pages are downloaded now. Only a mangadex placeholder that asks users to read at the main website itself

**Comment by nnti3n** [comment]
Me too @danbulant

**Comment by danbulant** [comment]
Will look into it, but for the past few days it was the case because of Mangadex mistakes (because of failed updates they had to disable all 3rd party readers, not just this one), but that should be resolved.

**Comment by nnti3n** [comment]
It works now. Thank you

**Comment by jonnyli** [comment]
Download no longer works now. Process  bar shows it starts but doesn't continue to move. No file is downloaded.

**Comment by danbulant** [comment]
@jonnyli can you provide more details? If there are any errors in console devtools (f12, console tab in the new window, errors have red background). Also try disabling cache (in the devtools window open the network tab and check disable cache).
Also please provide your browser (preferably with version), OS and a link to the manga you're trying to download.

I found out that viewing the manga directly and the list of covers was broken, but downloads were working. I now also fixed viewing the manga directly and the list of covers, so the page should be functional as it was before (changes might take a while to propagate).

**Comment by jonnyli** [comment]
@danbulant It works now. I'll be sure to take a look at the console next time if I encounter another issue. Thanks for the update!
