### ISSUE TITLE
generateEpub.js doesn't support multiple chapters

### ISSUE THREAD

**Issue by Funtime60** [danbulant/Mangades#9]
[generateEpub.js](https://github.com/danbulant/Mangades/blob/master/src/lib/util/generateEpub.js)

The code that generates xhtmls stomps on itself. At [Line 52](https://github.com/danbulant/Mangades/blob/56562f88ca2fdf81ef8d888feb24dbcc1b472cb1/src/lib/util/generateEpub.js#L52) it generates the xhtml for each page but the name doesn't take into account the chapter number so each chapter will generate its own page 0, 1, 2, etc...

The ultimate solution would be to calculate a page's absolute number in reference to all other chapters so it doesn't ever clobber.

**Comment by danbulant** [comment]
Fixed by b79647d
